---
application:
  name: "suporte-api-wp"
  project: "suporte-api"
  organization: "QoveryCommunity"
routers:
- name: "main-suporte-api-wp"
  routes:
  - application_name: "suporte-api-wp"
    paths:
    - "/*"
